### ワードデータ取得
GET http://localhost:3000/notion-word
Accept: application/json

### カテゴリーデータ取得
GET http://localhost:3000/notion-category
Accept: application/json

### タイプデータ取得
GET http://localhost:3000/notion-type
Accept: application/json

### 新規ワード追加(ロールバック不可)
POST http://localhost:3000/notion-request-word
Content-Type: application/json

{
    "word": "テストワード",
    "explanation": "これはテスト用の説明です。",
    "userId": "test-user"
}

### 周知データ取得
GET http://localhost:3000/notion-announcements
Accept: application/json

### 新規周知追加(ロールバック不可)
POST http://localhost:3000/notion-announcement
Content-Type: application/json

{
    "announceId": "テストid",
    "title": "テストtitle",
    "content": "テストcontent", 
    "created_at": "2025年3月11日 12:00"
}
